auto: true

markdown: Kramdown

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Ryan's Blog”
title: Ryan's Blog
description: Escape Plan
url: http://ryanwestinliu.github.io
feed: /atom.xml
author_info: <a href="http://ryanwestinliu.github.io/">Mukosame</a>
